apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: suhuruli/azure-vote-front
        env:
        - name: REDIS
          value: "redisbackend"
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisbackend
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: redis:alpine
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: redisbackend
  labels:
    app: db
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379